name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                default: '1.0.0'
            prerelease:
                description: 'Prerelease'
                required: true
                type: boolean
                default: false

permissions: write-all

jobs:
    release:
        name: Release RMMV-Core
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm install
              working-directory: ./src
            - name: Build
              run: npm run package
              working-directory: ./src
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rmmv-core
                  path: src/rmmv-core.zip
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ inputs.version }}
                  name: Release v${{ inputs.version }}
                  draft: false
                  prerelease: ${{ inputs.prerelease }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  generate_release_notes: true
                  files: src/rmmv-core.zip
                  target_commitish: ${{ github.ref_name }}