name: Twitter Release

on:
    release:
        types: [released]

jobs:
    tweet:
        name: Tweet
        runs-on: ubuntu-latest
        steps:
            - name: Tweet
              uses: Lulalaby/tweet@v2.0.0
              with:
                status: |
                  Released ${{ github.event.release.name }}
                  ${{ github.event.release.html_url }}
                media_paths: |
                  rccb.png
              env:      
                CONSUMER_API_KEY: ${{ secrets.AITSYS_CONSUMER_KEY }}
                CONSUMER_API_SECRET_KEY: ${{ secrets.AITSYS_CONSUMER_SECRET }}
                ACCESS_TOKEN: ${{ secrets.AITSYS_ACCESS_TOKEN_KEY }}
                ACCESS_TOKEN_SECRET: ${{ secrets.AITSYS_ACCESS_TOKEN_SECRET }}
